[mgr]
prepend_keymap = [
  { on = [ "g", "S" ], run = "shell '$HOME/.local/bin/mount-smb-share.sh' --confirm", desc = "Mount SMB shares" },
  { on = [ "g", "s" ], run = "cd /run/user/1000/gvfs", desc = "Go to SMB shares" },
  { on = [ "c", "z" ], run = "shell 'zip -r \"$1.zip\" \"$@\"' --confirm", desc = "Create ZIP" },
  { on = [ "c", "Z" ], run = "shell '$HOME/.local/bin/create-protected-zip.sh \"$@\"' --confirm ", desc = "Create protected ZIP" },
  { on = [ "c", "t" ], run = "shell 'tar -czf \"$1.tar.gz\" \"$@\"' --confirm", desc = "Create tarball" },
]
